### ISSUE TITLE
404 errors for 'missing' resources

### ISSUE THREAD

**Issue by WiltshireKate** [jklotzsche-msft/PS.MTA-STS#23]
We're seeing a lot of 404 errors for 'missing' resources:
/favicon.ico
/sitemap.xml
/robots.txt
Would it be sensible to add these to the Function App? Most other errors are in small numbers and look to be random probing.
If not, I'll just increase the alerting threshold.
Other than that, it's all working really well, thank you for doing this @jklotzsche-msft

**Comment by jklotzsche-msft** [comment]
Hello @WiltshireKate, we also see this kind of probing at other deployments. You can ignore these "errors" by increasing the threshold like you mentioned already.
The MTA-STS deployment doesn't need these files. That's why we haven't added and don't plan on adding them.
Thank you for your feedback :-)
